apiVersion: apps/v1
kind: Deployment
metadata:
  name: fileshare
  labels:
    app: fileshare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fileshare
  template:
    metadata:
      name: fileshare
      labels:
        app: fileshare
    spec:
      initContainers:
        - name: mount-permissions-fix
          image: busybox
          command: ["sh", "-c", "chmod 777 /data"]
          volumeMounts:
            - mountPath: /data
              name: data
      containers:
        - name: nginx
          image: centosadmin/reloadable-nginx:1.12
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          volumeMounts:
            - mountPath: /etc/nginx/conf.d
              name: config
            - mountPath: /data
              name: data
      volumes:
        - name: config
          configMap:
            name: fileshare
        - name: data
          persistentVolumeClaim:
            claimName: fileshare
      