---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap2
data:
  default.conf: |    
      server {
          listen      80 default_server;
          server_name _;
          
          default_type text_plain;
          location / {
              return 200 '$hostname\n'
          }
      }
...
