---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      automountServiceAccountToken: false
      containers:
      - image: nginx:1.12
        name: nginx
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        ports:
          - containerPort: 80
        env:
          - name: KEY_ENV_TEST
            value: test_value
          - name: test1
#            valueFrom:
#              secretKeyRef:
#                name: secret1
#                key: test1
        envFrom:
          - secretRef:
              name: secret1
          - configMapRef:
              name: my-configmap
...